apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    openproject.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      openproject.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        openproject.network/backend: "true"
        openproject.service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: openproject
            - name: POSTGRES_PASSWORD
              value: p4ssw0rd
            - name: PGDATA
              value: /var/lib/postgresql/data/openproject
          image: postgres:13
          ports:
            - containerPort: 5432
              name: psql
          name: db
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
      restartPolicy: Always
      terminationGracePeriodSeconds: 3
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata
status: {}
