apiVersion: v1
kind: Pod
metadata:
  labels:
    openproject.network/backend: "true"
    openproject.service: seeder
  name: seeder
spec:
  containers:
    - args:
        - ./docker/prod/seeder
      env:
        - name: DATABASE_URL
          value: postgres://postgres:p4ssw0rd@$(DB_SERVICE_HOST):$(DB_SERVICE_PORT)/openproject?pool=20&encoding=unicode&reconnect=true
        - name: IMAP_ENABLED
          value: "false"
        - name: OPENPROJECT_CACHE__MEMCACHE__SERVER
          value: $(CACHE_SERVICE_HOST):$(CACHE_SERVICE_PORT)
        - name: OPENPROJECT_RAILS__RELATIVE__URL__ROOT
        - name: RAILS_CACHE_STORE
          value: memcache
        - name: RAILS_MAX_THREADS
          value: "16"
        - name: RAILS_MIN_THREADS
          value: "4"
        - name: OPENPROJECT_EDITION
          value: standard
      image: openproject/community:12
      name: seeder
      resources: {}
      volumeMounts:
        - mountPath: /var/openproject/assets
          name: opdata
  restartPolicy: OnFailure
  volumes:
    - name: opdata
      persistentVolumeClaim:
        claimName: opdata
status: {}
